version: "3.8"

name: go_app

services:
  go_server:
    image: go_app
    build: .
    depends_on:
      - psql
    ports:
      - "8080:8080"
    restart: unless-stopped
    container_name: server

  psql:
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    image: postgres:14-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    restart: unless-stopped
    container_name: psql


volumes:
  pg-data:
    driver: local
